/*
 * THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
 *
 * Run `npx ets` or `yarn ets` to regenerate this file.
 * Source: ./whitespace-control.ets
 */
/* eslint-disable */

export default function (props: unknown): string {
  let result = "";
  result += "This is some text.\n";
  if (true) {
    result += "This text will be on the next line.\n";
  }
  result += "This is on yet another next line.\n\nThis is some text.\n";
  result = result.replace(/\n$/, "");
  if (true) {
    result += " This text will be on the same line as that.\n";
    result = result.replace(/\n$/, "");
  }
  result += " This is still on the same line.\n\nThis is some text.\n\n";
  result = result.replace(/\n$/, "");
  if (true) {
    result += "This text will be on the next line.\n\n";
    result = result.replace(/\n$/, "");
  }
  result += "This is on yet another next line.\n\nThis is some text.\n\n";
  result = result.trimRight();
  if (true) {
    result += " This text will be on the same line as that.\n\n";
    result = result.trimRight();
  }
  result += " This is still on the same line.";
  return result;
}
